### PR TITLE
readme: update screenshot

### PR DESCRIPTION
**Pull request by cmdrkotori**
Update screenshot with new icon and logo appearance.

### CODE REVIEW

**Comment by cmdrkotori** [comment]
The screenshots on the website were a good afternoon's work in a painting program, and they will need updating too at some point.

**Comment by tbertels** [comment]
Shouldn't we change the avatar on https://github.com/mpc-qt?

**Comment by cmdrkotori** [comment]
Done. I also updated this repo's social preview with the new logo.

**Comment by tbertels** [comment]
Good idea!

**Pull request merged**
