### PR TITLE
Native file dialog of Qt6 will crash app on macOS Ventura(Maybe sonoma too).

### PR DESCRIPTION
**Pull request by face1es5**
Use qt-native file dialog if current system is macOS.

### CODE REVIEW

**Comment by cmdrkotori** [comment]
I'll approve this for the sake of people who make DIY builds.  However I can't support or provide Mac releases because I don't own a Mac.

**Comment by face1es5** [comment]
> I'll approve this for the sake of people who make DIY builds. However I can't support or provide Mac releases because I don't own a Mac.

If you want, I can provide compiled program on macOS.

**Comment by tbertels** [comment]
> > I'll approve this for the sake of people who make DIY builds. However I can't support or provide Mac releases because I don't own a Mac.
> 
> If you want, I can provide compiled program on macOS.

If you use it and can provide support for the mac code, I don't think [cmdrkotori](https://github.com/cmdrkotori) would be against it.
See also #227 as other removed mac code could be still useful.

**Comment by cmdrkotori** [comment]
Right. I could add you two as members of the organization so that you can edit/make releases and commit the needed code. This would also help the project continue should something suddenly happen to me.

**Comment by tbertels** [comment]
I can't talk for [face1es5](https://github.com/face1es5), but I'm surely invested in mpc-qt and don't plan to stop contributing in the foreseeable future.

**Comment by cmdrkotori** [comment]
Ok I've invited @tbertels to the org as a member. If all goes well I hope you don't mind if I make you the secondary owner in a month or so, as github warned me about having only one owner. (Collaborating like this is all new to me.)

That said, from now on I'll try to make my commits PRs instead of straight on to master.

**Comment by cmdrkotori** [comment]
I'm not sure when's a good time to branch, beginning of December sounds good for an end of December release. Although I'm usually busy with advent of code during the later half of December as the puzzles get harder.  The chief reason I chose then was to give the appearance of a regular schedule so that perhaps one day we can end up in distros.  Anyway, if it doesn't work out we can move the release schedule around a little.

**Comment by tbertels** [comment]
We could branch in early to mid November to hopefully release in mid December.
There's just one minor feature I'd like to squeeze in, the rest is just bug fixes.

**Comment by tbertels** [comment]
> Ok I've invited @tbertels to the org as a member. If all goes well I hope you don't mind if I make you the secondary owner in a month or so, as github warned me about having only one owner. (Collaborating like this is all new to me.)
> 
> That said, from now on I'll try to make my commits PRs instead of straight on to master.

Thank you for adding me as an owner! 🥳

Apart of making commits, maintainers don't seem to have much more rights than normal users, they can't even merge pull requests or close issues.

**Comment by cmdrkotori** [comment]
>Apart of making commits, maintainers don't seem to have much more rights than normal users, they can't even merge pull requests or close issues.

Odd. In the organisation page it says you have admin access because you are an owner. In any case I just explicitly added you as admin here.

**Comment by cmdrkotori** [comment]
Ok, I see.

**Pull request merged**
