### PR TITLE
Build script updates

### PR DESCRIPTION
**Pull request by cmdrkotori**
These are the last minute changes to the build scripts I had to make today when building the latest release.  As you can see, pretty benign stuff.

### CODE REVIEW

**Comment by cmdrkotori** [comment]
This lacks the project file edit of replacing the line `unix:PKGCONFIG += mpv` with `unix:LIBS += -lmpv` for the [unique build environment](https://github.com/mpc-qt/mpc-qt/issues/128#issuecomment-2131177394) required to build the AppImage on Ubuntu 20.04.

**Comment by tbertels** [comment]
On the subject, is there any reason to have both `make-release-msys2.sh` and `make-release-win.sh` or could the release be made by the GitHub action?

For the AppImage, we could probably automate it too if we build or download newer dependencies than on the Ubuntu system.
I just saw your comment, we can force use ubuntu-24.04 before it becomes the default this month.

**Comment by cmdrkotori** [comment]
>On the subject, is there any reason to have both make-release-msys2.sh and make-release-win.sh or could the release be made by the GitHub action?

The big reason why make-release-win is used is because it results in a smaller directory listing due a static build of libmpv, and it bundles yt-dlp.  The second reason is I have no experience in making releases from Github actions.

>For the AppImage, we could probably automate it too if we build or download newer dependencies than on the Ubuntu system.
>I just saw your comment, we can force use ubuntu-24.04 before it becomes the default this month.
>Update: It seems like we actually want the opposite: force use ubuntu-20.04.

I see no reason not to do this.

**Comment by tbertels** [comment]
> > On the subject, is there any reason to have both make-release-msys2.sh and make-release-win.sh or could the release be made by the GitHub action?
> 
> The big reason why make-release-win is used is because it results in a smaller directory listing due a static build of libmpv, and it bundles yt-dlp. The second reason is I have no experience in making releases from Github actions.

I'm sure we could download automatically the libmpv and yt-dlp builds like you do it manually for the release. We could even host a backup of them in a different repository if needed.
I can work on it to make the future releases easier.

> > For the AppImage, we could probably automate it too if we build or download newer dependencies than on the Ubuntu system.
> > I just saw your comment, we can force use ubuntu-24.04 before it becomes the default this month.
> > Update: It seems like we actually want the opposite: force use ubuntu-20.04.
> 
> I see no reason not to do this.

Do you mean you don't see a reason to automate the AppImage or the part about the Ubuntu versions?

I see the AppImage as a way for users to be able to use mpc-qt even if they don't a way to automatically build it.
The executable artifact requires the right dependencies, so it's not actually that useful for users.

I was thinking of adding links to the latest continuous builds on the website like mpv does, but by using https://github.com/TheAssassin/pyuploadtool to upload the latest artifacts in a new repository and then link them from the website.
Because the users need to have an account to download the CI artifacts and it's not very user friendly anyway.

**Comment by cmdrkotori** [comment]
>I'm sure we could download automatically the libmpv and yt-dlp builds like you do it manually for the release. We could even host a backup of them in a different repository if needed.
>I can work on it to make the future releases easier.

Thanks. I'm not always at home with my rig to do manual builds as it is.

>Do you mean you don't see a reason to automate the AppImage or the part about the Ubuntu versions?

Sorry, I meant automating the appimage.  Actions can be on whatever ubuntu version the situation calls for.

>I see the AppImage as a way for users to be able to use mpc-qt even if they don't a way to automatically build it.
>The executable artifact requires the right dependencies, so it's not actually that useful for users.

Yes I agree.  Luckily we already have a make-release-linux script that can be cannibalized to do the appimage part. (finding the documentation for it wasn't easy.)

>I was thinking of adding links to the latest continuous builds on the website like mpv does, but by using https://github.com/TheAssassin/pyuploadtool to upload the latest artifacts in a new repository and then link them from the website.
>Because the users need to have an account to download the CI artifacts and it's not very user friendly anyway.

Sounds good.  The more testers the better.

>About the website, we probably want to replace the main screenshot with the one of the readme, even if we don't update the gallery yet.

I'll get to that once the release is out.

**Comment by cmdrkotori** [comment]
Oh, do you want to me to continue making the next release manually or wait until it's done by CI?

**Comment by tbertels** [comment]
> Yes I agree. Luckily we already have a make-release-linux script that can be cannibalized to do the appimage part. (finding the documentation for it wasn't easy.)

Yes, and your build instructions for Ubuntu 20.04 will be most useful.

> Oh, do you want to me to continue making the next release manually or wait until it's done by CI?

It's probably better if you do it manually this time as I don't know how long it'll take to prepare the CI or if it'll work at all.

**Comment by tbertels** [comment]
> > About the website, we probably want to replace the main screenshot with the one of the readme, even if we don't update the gallery yet.
> 
> I'll get to that once the release is out.

Nice, you've updated the favicon too! 🙂

**Pull request merged**
